// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPDGp0nLl0GSSsx2S70tQtsoPmQXQZw3s',
    appId: '1:836996424097:android:929f0e2c565b6c41cc2be0',
    messagingSenderId: '836996424097',
    projectId: 'ttlholidayinc',
    storageBucket: 'ttlholidayinc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtCskRdA87WYl3RDtXLZJSt3CKLlSB5JE',
    appId: '1:836996424097:ios:d6048cc3f89404cacc2be0',
    messagingSenderId: '836996424097',
    projectId: 'ttlholidayinc',
    storageBucket: 'ttlholidayinc.appspot.com',
    androidClientId: '836996424097-49epa1utfr0uh3vdgqjcp6rvckjv4qt8.apps.googleusercontent.com',
    iosClientId: '836996424097-q2ieq8tpm7baai04o87bds4poh0ugdc9.apps.googleusercontent.com',
    iosBundleId: 'com.ttlHoliDaysInCone.flyDealFare',
  );
}
